// Update the Node patch/minor release without maintaining Bazel hashes by hand.
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const version = process.argv[2];
const runtime = JSON.parse(
  fs.readFileSync(path.join(root, "apps/web/vercel-build.json"), "utf8"),
).nodeVersion;
if (
  !/^\d+\.\d+\.\d+$/.test(version || "") ||
  !runtime.startsWith(`${version.split(".")[0]}.`)
) {
  throw new Error(
    `Usage: node scripts/update-node.mjs VERSION, within Vercel's configured ${runtime}`,
  );
}
const response = await fetch(
  `https://nodejs.org/dist/v${version}/SHASUMS256.txt`,
);
if (!response.ok) throw new Error(`Node checksums: HTTP ${response.status}`);
const checksums = new Map(
  (await response.text())
    .trim()
    .split("\n")
    .map((line) => {
      const [hash, filename] = line.trim().split(/\s+/);
      return [filename, hash];
    }),
);
const platforms = {
  darwin_arm64: ["darwin-arm64", "tar.gz"],
  darwin_amd64: ["darwin-x64", "tar.gz"],
  linux_arm64: ["linux-arm64", "tar.xz"],
  linux_amd64: ["linux-x64", "tar.xz"],
  linux_ppc64le: ["linux-ppc64le", "tar.xz"],
  linux_s390x: ["linux-s390x", "tar.xz"],
  windows_arm64: ["win-arm64", "zip"],
  windows_amd64: ["win-x64", "zip"],
};
const entries = Object.entries(platforms).map(
  ([platform, [host, extension]]) => {
    const prefix = `node-v${version}-${host}`;
    const filename = `${prefix}.${extension}`;
    const hash = checksums.get(filename);
    if (!/^[a-f0-9]{64}$/.test(hash || ""))
      throw new Error(`Missing checksum for ${filename}`);
    return `        "${version}-${platform}": ["${filename}", "${prefix}", "${hash}"],`;
  },
);
const module = `# Generated by scripts/update-node.mjs from Node's official SHASUMS256.txt.
node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(
    node_version_from_nvmrc = "//:.nvmrc",
    node_repositories = {
${entries.join("\n")}
    },
)
`;
fs.writeFileSync(path.join(root, "tools/bazel/node.MODULE.bazel"), module);
fs.writeFileSync(path.join(root, ".nvmrc"), `${version}\n`);
const tools = path.join(root, ".tool-versions");
fs.writeFileSync(
  tools,
  fs.readFileSync(tools, "utf8").replace(/^nodejs .+$/m, `nodejs ${version}`),
);
console.log(`Pinned Node ${version} for Bazel, local development and CI.`);
